### ISSUE TITLE
Fix clippy warnings

### ISSUE THREAD

**Issue by luisbg** [mbrubeck/robinson#15]
This will make the already very educational code more readable.

Please tag this issue as 'Hacktoberfest' :smile: 

Thanks so much for your "Let's build a browser engine!" series. Really cool.

**Comment by luisbg** [comment]
PR #14 is part of this issue

**Comment by luisbg** [comment]
PR #16 also is part of this issue :+1:

**Comment by luisbg** [comment]
And one more, PR #17

**Comment by mbrubeck** [comment]
Thank you!

**Comment by luisbg** [comment]
My pleasure. Thanks for merging.
